# Configure Splunk REST API with SSL
---

- name: Configure Splunk REST API with SSL
  become_user: splunk  # should be replaced with the correct user if different
  lineinfile:
    path: /opt/splunk/etc/system/local/web.conf 
    regexp: "^(httpport|enableSplunkWebSSL|privKeyPath|caCertPath|serverCert|sslVersions) ="
    line: |
      httpport = 443
      enableSplunkWebSSL = true
      privKeyPath = /path/to/your/private/key.key
      caCertPath = /path/to/your/ca-certificate.pem
      serverCert = /path/to/your/server-certificate.pem
      sslVersions = tls1.2, tls1.3  # Specify supported SSL/TLS versions
# put the correct data/paths in the section above

# - name: Configure REST API Data Collection
#   lineinfile:
#     path: "{{ splunk_inputs_conf }}"
#     line: |
#       [http://localhost:8080]
#       disabled = false
#       index = rest_api_logs
