# Starting Splunk
---

- name: Start Splunk Service
  command: "{{ splunk_home }}/bin/splunk start --accept-license --answer-yes --no-prompt"
  async: 1800
  poll: 0
  register: splunk_start_result

- name: Wait for Splunk to Start
  async_status:
    jid: "{{ splunk_start_result.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 180
  delay: 10

- name: Check Splunk Service Status
  command: "{{ splunk_home }}/bin/splunk status"

- name: Configure Splunk License
  command: "{{ splunk_home }}/bin/splunk add licenses {{ splunk_license_path }}/license-file.lic"

- name: Enable REST API Integration
  command: "{{ splunk_home }}/bin/splunk http-event-collector enable"

# - name: Configure SSL/TLS
#   copy:
#     src: /path/to/ssl_cert.pem
#     dest: "{{ splunk_home }}/etc/auth/server.pem"